baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
publishDir = "../public"

[module]
  [[module.imports]]
    path = "github.com/clente/hugo-bearcub"

theme = "hugo-bearcub"